### ISSUE TITLE
Counts of various things for Secchi depth example

### ISSUE THREAD

**Issue by eread-usgs** [USGS-R/geolakes#20]
These three tasks should happen *after* the removal of duplicate records is done, see #21.

- [x] Number of duplicate records (same lat/long, date, and value)- this is pending the removal of duplicate records. 
- [x] Number of results removed due to missing units (after duplicates removed)
- [x] Number of outliers removed after removal of duplicates (after duplicates and missing units removed)
- [x] Table for supplemental materials including counts for each region (columns) for each weekly bin (rows)

**Comment by ldecicco-USGS** [comment]
Number of duplicates = 47,927
Number of values over 150 or under 0 = 581

The missing units is actually done during the retrieval (as it's set up now). I'll re-write that and get those numbers after a meeting.

**Comment by ldecicco-USGS** [comment]
OK, here's how the script goes right now:

2,316,205 rows come in raw
Then I filter:
```
ActivityTypeCode %in% c("Field Msr/Obs","Sample-Routine",
                                 "Field Msr/Obs-Portable Data Logger",
                                 "Sample-Composite Without Parents",
                                 "Sample-Field Split","Sample-Other")
```
to get 2,289,964 records (so, **dropping 26,241 records**)

Then, I filter out only ActivityMediaName in c("Water","Other","Habitat"), that drops to:
2,289,355 records (so, **dropping 609** more records)

**Comment by ldecicco-USGS** [comment]
Then we drop records that aren't associated with a region (they don't have state names, or are territories like Guam), that brings us to:
2,086,138 (**dropping 203,216**)

**Comment by ldecicco-USGS** [comment]
From there, there are **346,056 duplicated records** based on Date, lat, lon, value, bringing us to 1,740,083 records

**Comment by ldecicco-USGS** [comment]
Finally, we **drop 519,617** records that are outside of 0-46 m.

Leaving 1,220,466 records...before @jread-usgs filters with PIP.

**Comment by jordansread** [comment]
If we are using lat/lon I don't think we need region metadata

**Comment by jordansread** [comment]
wow, that is a lot of records that are <0 or > 46m.

**Comment by ldecicco-USGS** [comment]
yeah, I'm messing around to see what's what. Negative values for example might just need to be taken the absolute value? I could imagine thinking that might be correct.

**Comment by jordansread** [comment]
yes, because some may be thinking depth as negative z

**Comment by ldecicco-USGS** [comment]
As for region...that's what the graph is plotting though....

**Comment by jordansread** [comment]
but we can do PIP with the states to figure that out. If we are using the lat/lon as the absolute location for the site, I think we should also use that to figure out region.
