### ISSUE TITLE
Add column and row headings to figure 1

### ISSUE THREAD

**Issue by eread-usgs** [USGS-R/geolakes#23]
Per 2 reviewers' request. 
![screen shot 2017-01-03 at 1 49 30 pm](https://cloud.githubusercontent.com/assets/7794368/21620764/798ffba8-d1bb-11e6-8af9-9b36e37e3d95.png)

**Comment by eread-usgs** [comment]
@jread-usgs friendly reminder about this one, too. thx.

**Comment by jordansread** [comment]
![multi_panel_constituents](https://cloud.githubusercontent.com/assets/2349007/21664800/74e43328-d2ae-11e6-89b7-c89a4be6488a.png)


@eread-usgs ☝️ ?

**Comment by jordansread** [comment]
see #24
