### ISSUE TITLE
update "createFig1" to include the recent changes to the mapping functions

### ISSUE THREAD

**Issue by jordansread** [USGS-R/geolakes#26]
https://github.com/USGS-R/geolakes/pull/25/files#diff-e9e72945de0b2b62d8edfa49da260719R96 and more

**Comment by lindsayplatt** [comment]
confused...isn't that PR showing the updated code

**Comment by jordansread** [comment]
It is a different file than the R/createFig1.R file I was referring to. But I see here that the example code only produces one map, so it doesn't need to change. if that is the case @lindsaycarr you can close this issue.

**Comment by lindsayplatt** [comment]
Yes, those changes only impacted the function `plot_huc_panel`, which is not used by the `createFig1` code because it is only producing a map of lake temperature, and then a map of all phosphorus separately.
